include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/l10n/messages_*.dart
    - lib/l10n/l10n.dart
    - lib/l10n/intl/*.dart
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/generated/*.dart
