name: base
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  mocktail: ^1.0.4
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.2
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  curl_logger_dio_interceptor: ^1.0.0
  awesome_dio_interceptor: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  mockito: ^5.4.4
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter_gen:
  output: lib/generated/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

# TODO: update your splash configuration
# flutter_native_splash:
#   android: true
#   ios: true
#   web: true
#   color: "#FFFFFF"
#   image: assets/images/app_logo.png
#   ios_content_mode: center
#   web_image_mode: center
#   fullscreen: true

#   android_12:
#     image: assets/images/android12splash.png
#     icon_background_color: "#FFFFFF"
#     color: "#FFFFFF"

# TODO: update localization configuration
# flutter_intl:
#   enabled: true # Required. Must be set to true to activate the package. Default: false
#   class_name: L10n # Optional. Sets the name for the generated localization class. Default: S
#   main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
#   arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
#   output_dir: lib/l10n # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
#   use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/
